Document how to install for Fedora
sile-typesetter/sile pull request #1629
Opened 2022-11-25 15:45 UTC by hegjon

Install from COPR for now

2022-11-29 07:35 UTC, alerque commented on README.md
> +packages added to the official Fedora repository.
```suggestion
Fedora 36 and Fedora 37 are supported.
There is work in progress to get the packages added to the official Fedora repository.
```

2022-11-29 07:38 UTC, alerque requested changes
Lets add this same info to the manual too. Do you want me to cover that?

2022-11-29 07:38 UTC, alerque commented on README.md
> +$ sudo dnf install sile
Lets not suggest sudo here, we kind of expect users to be able to adapt to their own system admin style whether that is a root shell (yuck) or sudo or doas or whatever. We don't suggest this for other distros either.

```suggestion
$ dnf copr enable jonny/SILE
$ dnf install sile
```

2022-11-30 11:18 UTC, merged

2022-11-30 11:22 UTC, hegjon commented
> Lets add this same info to the manual too. Do you want me to cover that?

Yes, I did not think about the manual