docs(manual): Add section on measurements and lengths
sile-typesetter/sile pull request #1768
Opened 2023-04-09 22:52 UTC by Omikhleia

Close #1267 (well, the last unaddressed checkbox)

In chapter Chapter 9 (The Nitty Gritty):
- Add "Measurements and lengths" new section (moving content from below and extending it)
- Slightly refactor "Boxes, glue, and penalties" section as appropriate.
- Move "Kerns" (sub)section closer to the above (sounds more logical, as of introducing concept progressively)
- Split "The typesetter" section apart below these

In all the above, add a bit more of autodoc's magic here and there.

2023-04-09 23:10 UTC, Omikhleia commented on documentation/c09-concepts.sil
> +local l3 = SILE.length(SILE.measurement("10pt")) -- 10pt, without strech and shrink
"without strech ..." --> "without stretch'. It seems I cannot get this word right, despite knowing I do the same mistake over and over :)

2023-04-09 23:27 UTC, Omikhleia commented on documentation/c09-concepts.sil
> +local l3 = SILE.length(SILE.measurement("10pt")) -- 10pt, without strech and shrink
Fixed in a separate commit: a few other occurrence (not mine only, pfew).

2023-04-10 08:01 UTC, alerque requested changes

2023-04-10 08:05 UTC, alerque approved these changes

2023-04-10 08:38 UTC, merged