Command \center now has an option to center its content vertically
sile-typesetter/sile pull request #1898
Opened 2023-10-21 21:33 UTC by jodros

I found this command was lacking an option to do the centering vertically (like asked here #475).

2023-10-21 21:41 UTC, jodros commented
I'm unsure whether I should write the following after the settings:temporarily block

```lua
if SU.boolean(options.vertical) and then
      SILE.call("eject")
end
```

2023-10-22 16:22 UTC, Omikhleia commented on classes/plain.lua
> +      SILE.call("vfill")
A vfill won't push the content middle of the page, _unless_ if it is a final page automatically vfill'ed (such as the final page of your example) or explicitly `\eject`'ed. Then another vfill is currently automatically added at the end of the page, resulting in centering.

Personally:
- I don't think that horizontal centering and vertical centering should be the same command
- I don' think the vfill added on final pages or via eject is actually good :)

2023-10-23 09:12 UTC, alerque requested changes
I think @Omikhleia is right here, writing direction (linewise) centering and advance direction (framewise) are very different operations and don't belong in the same command. In fact any sort of advance direction centering (absolute to page?, relative to frame), fill available remaining space?) is so complicated and the interactions with line spacing, start-of-frame and end-of-frame queues, and so forth is so complicated that this should go in a dedicated package and even if all possible modes are not implemented at first, some thought should be given to the command names(s) so that the rest of the scenarios can be implemented without stepping all over existing documents.

I don think that some centering handlers are sufficiently basic enough and used as building blocks for other commands that this is something the core distribution should provide, so adding a package in this repo is probably warranted.

2024-10-19 21:40 UTC, Omikhleia commented
This old PR now has conflicts, and last discussions pointed it would not occur as-is.
I am closing it, but please feel free to re-open a dedicated issue and/or PR if a different approach should be discussed.

2024-10-19 21:40 UTC, closed without merging