Fix on command makecolumns
sile-typesetter/sile pull request #1901
Opened 2023-10-22 07:17 UTC by jodros

The problem is explained in #1900

2023-10-23 10:56 UTC, alerque commented
c.f. #420

2023-10-23 10:59 UTC, alerque reviewed
How does this fare when *reducing* the number of columns (as noted is a problem in #248) and/or subsequently changing the value after doing it once? Fixing those cases might not be blockers for this PR but we should at least track whether they are fixed or not.

2023-10-23 13:10 UTC, jodros commented
I began to play with \makecolumns just after reading the issue #248, so I have interest in finding a solution for it as well...

> c.f. #420

You mention have done a "dirty hack", well, this description:

> adding ALL the broken frame id's to the insertion steal from list and iterating over ones that exist on a given page

looks like my own approach, why would it be a "dirty hack"? How should a clean fix look like?

2023-10-27 10:25 UTC, alerque commented
Sorry I seem to have inadvertently edited *your comment* instead of *reply to selection*! I restored your comment and here is my reply:

> why would it be a "dirty hack"? How should a clean fix look like?

It doesn't take into account things like the possibility of splitting frames (say to add a float) after starting columns, or ending columns after they are started. You don't want insertions stealing space from anything but the actually *adjacent* frames. Ones that were adjacent at one time but later got split or whatever shouldn't be eligible for theft.

2023-10-27 11:40 UTC, alerque commented
LOL, so I tried to fix this to work in any direction, but it turns out the column splitter assumes the direction anyway, and this isn't the right output either:

![20231027_14h39m11s_grim](https://github.com/sile-typesetter/sile/assets/173595/91138eed-22b7-4651-b76e-0a72d3b77a42)

Good times. I do think the code I added will be useful later when `makeoptions()` takes into account the frame advance direction, but for now I'll backtrack a little bit to assuming "right" again.

2023-10-27 11:55 UTC, alerque commented
@jodros How does my last commit here look to you? It turns out it isn't too useful since it still only works in the `:right()` direction, but I hopefully this will make it easier not harder to eventually expand the column tooling to automatically generate columns in any advance direction.

2023-10-27 12:06 UTC, alerque requested changes

2023-10-27 12:06 UTC, alerque commented on tests/makecolumns.sil
> +\script[src=packages/frametricks]
@jodros I'll fix this test, but just for your own reference in the future, the non-deprecated syntax for this is:

```suggestion
\script[src=packages/frametricks]
\use[module=packages.frametricks]
```

2023-10-27 12:26 UTC, alerque submitted a review, later dismissed

2023-10-27 19:39 UTC, alerque commented
Please don't merge from master into feature branches unless there is a real reason to do so, such as the feature being worked on being dependent on something else that landed. It just makes history tracking / git blame / etc. much harder to work with.

2023-10-27 21:19 UTC, Omikhleia commented
> Please don't merge from master into feature branches unless there is a real reason to do so, such as the feature being worked on being dependent on something else that landed. It just makes history tracking / git blame / etc. much harder to work with.

Rebase is _always_ a good friend ;)

2023-10-29 02:01 UTC, jodros commented
> Please don't merge from master into feature branches unless there is a real reason to do so, such as the feature being worked on being dependent on something else that landed. It just makes history tracking / git blame / etc. much harder to work with.

Sorry, I didn't know it was a problem, I just reverted the merging right now.

2023-10-30 08:20 UTC, alerque approved these changes

2023-10-30 08:20 UTC, merged