Only call 'noindent' if language is English
sile-typesetter/sile pull request #1991
Opened 2024-02-06 03:28 UTC by jodros

Since it's a English feature it shouldn't be called if `document.language` isn't English as well...

2024-02-06 10:04 UTC, alerque requested changes
No, sorry that source comment is misleading. This is not an "English" feature, it is quite a common default for many languages that use Latin based orthographies. For example Turkish ;-)

The more relevant point is that there are a handful of languages that specifically eschew this: French being a notable one. I think the correct approach here will be to make this behavior have a per-language default. That isn't easy to do right no because of the chaotic overlap in scopes for the language modules, but I'm actually refactoring that right now and am hopeful we'll have a better place to "hang this hat" soon. I'll leave this PR around as a reminder of the issue and we'll update it to to the right thing when there is a sensible way to do so.

2024-02-06 20:22 UTC, jodros commented
>  (As an aside note, in a styling paradigm such as your @jodros, or mine, this could be left to a styling decision)

yeah, I thought about that, and I really think that we should discuss further the implementation of a basic styling paradigm in SILE, this is essencial for typesetting, maybe many problems of SILE would be "solved" if it had one fully changeable by the end-user...

2024-05-06 21:53 UTC, Omikhleia commented
An interesting discussion on the topic: https://tex.stackexchange.com/a/39232

(The whole discussion mentions typographers such as Bringhurst, Tschichold; and the French _Imprimerie Nationale_ -- all sorts of lectures I personally like)

There _could_ be a language-specific default, thus...
--> Linking to #2017 as we might need some other language-specific customization there too.

2024-10-19 21:42 UTC, Omikhleia commented
This old PR now has conflicts, and last discussions pointed it would not occur as-is.
I am closing it, but please feel free to re-open a dedicated issue and/or PR if a different approach should be discussed.

2024-10-19 21:42 UTC, closed without merging